version: '3.7'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}  
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
      
 